package fun.eversense.api.storages.implement.helpertstorages.enumvar;


import fun.eversense.client.modules.Module;

import java.util.List;

public class ModuleClass extends GlobalObject<Module> implements ModuleRewords {

    public static ModuleClass INSTANCE = new ModuleClass();

    public void initialize() {
        this.add(
                antibot,
                aimBot,
                airStuck,
                arrows,
                aura,
                autoAccept,
                autoArmor,
                autoCart,
                autoBuy,
                autoDuel,
                autoEat,
                autoLeave,
                autoExplosion,
                autoForest,
                autoJoin,
                autoPotion,
                autoPvp,
                nameProtect,
                autoFish,
                autoJump,
                autoBuy,
                autoSwap,
                autoTool,
                autoTotem,
                autoTrap,
                blockesp,
                blockOverlay,
                chams,
                chestStealer,
                clickFriend,
                clientSounds,
                clickPearl,
                cosmetics,
                cubes,
                deathCoord,
                ecopen,
                elytraBoost,
                elytraMotion,
                elytraSwap,
                forward,
                elytraresolver,
                entityESP,
                fireworkESP,
                fastBreak,
                fastExp,
                flight,
                freeCam,
                fullBright,
                grimGlide,
                grimNoFall,
                highJump,
                helpMessage,
                hitBubbles,
                hitMarker,
                hitSonar,
                interfaceModule,
                interpolateF5,
                inventoryWalk,
                itemAim,
                itemRelease,
                itemScroller,
                jumpCircle,
                killEffect,
                kTLeave,
                leavetracker,
                lineGlyphes,
                lockSlot,
                lootTracker,
                noClip,
                noFriendDamage,
                noJumpDelay,
                nuker,
                noPush,
                noSlow,
                noVelocity,
                noVignette,
                noControllerWeb,
                noWeb,
                packetCriticals,
                particle,
                playerFakeLags,
                projectile,
                scoreboardHP,
                removals,
                rPSpoofer,
                sattelite,
                seeInvisibles,
                shaderEsp,
                shaderHands,
                serverHelper,
                shulkerPreview,
                sonar,
                speed,
                spider,
                sprint,
                step,
                swingAnimations,
                targetESP,
                targetPearl,
                timer,
                totemAngel,
                tpsSync,
                tpBack,
                tpLoot,
                trails,
                trajectories,
                triggerBot,
                viewModel,
                worldTweaks,
                xCarry
        );
    }

    private void add(final Module... mod) {
        this.getObject().addAll(List.of(mod));
    }
}
